### ISSUE TITLE
Consider using SassDoc

### ISSUE THREAD

**Issue by HugoGiraudel** [drublic/Sass-Mixins#37]
You are using JSDoc-like comments already, so you might as well want to be [SassDoc](http://sassdoc.com)-compatible in order to provide a fully-designed API documentation, ideally on a `gh-pages` branch to keep it simple.

If you need help with transition, be sure to ask Hans. :)

**Comment by JHeimbach** [comment]
Hey drublic,

are you interested in converting the comment to sassDoc? I would do if you want it :)

**Comment by drublic** [comment]
Sure. I'd love to see a PR for that.

**Comment by drublic** [comment]
See #48.
